# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Qualifications
    url: qualifications/
    weight: 11
  - name: Research
    url: research/
    weight: 12
  - name: Projects
    url: projects/
    weight: 13
  # - name: Awards and honors
  #   url: awards/
  #   weight: 30
  - name: CV
    url: uploads/Academic_CV_Chowdhury_Ahmed_Hossain.pdf
    weight: 999
