# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: red

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: "I am Chowdhury Ahmed Hossain, a Mechanical Engineering PhD Student at University of Houston. As a research assistant at Dr. Theocharis Baxevanis's lab, I am working on bistable auxetic materials. My broad research interest lies in integrating experimental methods with computational modeling to better understand behavior of advanced materials and improve their properties to tackle complex engineering challenges."
    twitter: 'chowdhury_sami0'
  analytics:
    google_tag_manager: 'GTM-N4J35WK5' 
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: "right"
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: false
    logo:
      text: ""
      filename: "logo.png"

# Site footer
# footer:
#   copyright:
#     notice: '© {year} Chowdhury Ahmed Hossain. This work is licensed under {license}'
#     license:
#       enable: true
#       allow_derivatives: false
#       share_alike: true
#       allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
  avater:
    shape: circle
    # Avater size in px > if 250px by 250x input 250x250
    size: '250x250'

# CMSs
extensions:
#   decap_cms:
#     branch: main
# #     publish_mode: editorial_workflow
#     local_backend: true