# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: red

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: "I am Chowdhury Ahmed Hossain, a recent Mechanical Engineering graduate from the Bangladesh University of Engineering and Technology (BUET). Driven by curiosity and a love for solving problems, I have worked on numerous mechanical design and research projects, becoming proficient in various design and analysis software, experimental and simulation techniques, and developing a strong programming background. I thrive on learning new things, whether it’s understanding an academic concept or picking up a new language. When I’m not doing any of these, you may find me roaming the streets, watching anime, or playing video games. Currently, I’m looking for PhD opportunities for fall 2025, focusing on Material Behavior, Computational Mechanics, Advanced Materials, and Additive Manufacturing. My goal is to develop novel materials with tailored properties to tackle complex engineering challenges. I am particularly interested in integrating experimental methods with computational modeling to better understand material behavior and improve material design."
    twitter: 'chowdhury_sami0'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    align: "right"
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: false
    logo:
      text: "Chowdhury Ahmed Hossain"
      filename: "logo.png"

# Site footer
footer:
  copyright:
    notice: '© {year} Me. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
  avater:
    shape: circle

# CMSs
extensions:
  decap_cms:
    branch: main
#     publish_mode: editorial_workflow
    local_backend: true